baseUrl      = "https://jadolan.github.io"
title        = "Jana Dolan"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Engineer | Berlin"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Jana Dolan – Software Engineer"
  keywords = "homepage, blog"
  images = [""]

    [params.footer]
    trademark = true
    copyright = true
    author = true

    topText = []
    bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
            "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]

    [[params.social]]
    name = "email"
    url = "mailto:jana.dolan@posteo.de"

    [[params.social]]
    name = "github"
    url = "https://github.com/jadolan"

    [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jana-dolan-692514215"

[languages]
  [languages.en]
    title = "Jana Dolan"
    subtitle = "Software Engineer"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">MIT</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "welcome"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  #[[menu.main]]
  #  identifier = "blog"
  #  name       = "Blog"
  #  url        = "/posts"

  [author]
  name = "Jana Dolan"
  homepage = "https://jadolan.github.io/"