name: Build and Deploy Hugo to GHP

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.93.0
        TARGET_REPO: jadolan/jadolan.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.HUGO_DEPLOY_SECRET }}
